export type Product = {
  id: string;
  slug: string;
  name: string;
  brand: string;
  category: 'mouth-tape' | 'nasal' | 'gadgets' | 'mattresses' | 'supplements' | 'bedding';
  rating: number; // 0-5
  reviewCount: number;
  price: string; // e.g. "£13.49 / 30 strips" (GBP for UK/international compatibility)
  priceValue: number; // for sorting
  bestFor: string[]; // tags
  pros: string[];
  cons: string[];
  description: string;
  longDescription: string;
  safetyNotes: string[];
  howToUse: string[];
  ingredients?: string;
  affiliateLink: string; // base destination. Can be overridden via env vars in lib/affiliates.ts (recommended)
  amazonAsin?: string; // Optional: ASIN for Amazon Associates link (preferred for many products)
  image: string;
  featured?: boolean;
  inStock?: boolean;
};

export const mouthTapeProducts: Product[] = [
  {
    id: 'p1',
    slug: 'dream-recovery',
    name: 'Dream Recovery Mouth Tape',
    brand: 'Dream Recovery',
    category: 'mouth-tape',
    rating: 4.8,
    reviewCount: 1243,
    price: '£13.49 / 30 strips',
    priceValue: 13.49,
    bestFor: ['Side Sleepers', 'Sensitive Skin', 'CPAP Users'],
    pros: [
      'Gentle medical-grade adhesive, no residue',
      'Breathable fabric that feels invisible',
      'Excellent for side sleepers – stays put all night',
      'CPAP mask compatible (many users report)',
      'Hypoallergenic and latex-free',
    ],
    cons: [
      'Premium price compared to basic tape',
      'Only 30 strips per pack (some competitors offer more)',
      'May feel too gentle for heavy mouth breathers initially',
    ],
    description: 'Premium gentle mouth tape designed specifically for sleep. Medical-grade, skin-friendly, and trusted by thousands for quiet nights and falling asleep faster.',
    longDescription: 'Dream Recovery sets the standard for premium sleep mouth tape in 2026. Developed with input from sleep dentists and ENTs, these strips use a proprietary low-tack adhesive that holds strong through the night but removes easily without irritation. The soft, flexible material moves with your face and works especially well for side and stomach sleepers. Many users report reduced sleep anxiety from consistent nasal breathing and fewer dry-mouth awakenings that can worsen insomnia symptoms.',
    safetyNotes: [
      'Do not use if you have nasal congestion, cold, or allergies that prevent nasal breathing.',
      'Not recommended for children under 12 without medical supervision.',
      'Consult your doctor before use if you have sleep apnea (unless using with CPAP).',
      'Test on skin for 30 mins before first full night use.',
      'Remove immediately if you experience difficulty breathing or discomfort.',
    ],
    howToUse: [
      'Clean and dry lips before application.',
      'Peel strip and center over closed lips.',
      'Press gently for 5 seconds to adhere.',
      'Breathe only through your nose.',
      'In morning, slowly peel from one corner.',
    ],
    affiliateLink: 'https://www.amazon.co.uk/s?k=premium+mouth+tape+for+sleep&tag=stewraw25-21',
    amazonAsin: 'B0CBCQ8YT6', // Longevity Sleep Tape (gentle, derm-tested 30pk) - good match for premium gentle tape; credits stewraw25-21
    image: '/images/dream-recovery-tape.jpg',
    featured: true,
    inStock: true,
  },
  {
    id: 'p2',
    slug: 'somnifix',
    name: 'SomniFix Sleep Strips',
    brand: 'SomniFix',
    category: 'mouth-tape',
    rating: 4.6,
    reviewCount: 2891,
    price: '£18.99 / 28 nights',
    priceValue: 18.99,
    bestFor: ['Beards', 'Side Sleepers', 'CPAP Users'],
    pros: [
      'Patented "mouth strip" design with center vent for safety',
      'Works surprisingly well over facial hair',
      'Very strong hold yet comfortable',
      'Great for CPAP + mouth tape users',
      'Large pack options available',
    ],
    cons: [
      'Higher price point',
      'The vent can feel strange at first',
      'Some find adhesive slightly more aggressive on removal',
    ],
    description: 'The original "sleep strip" with a built-in safety vent. Popular choice for people with beards and CPAP users.',
    longDescription: 'SomniFix pioneered the mouth taping trend with their unique design featuring a small central vent that allows limited emergency airflow while still encouraging nasal breathing. This makes many users feel safer. The extra-wide design helps it stay secure even with beards and mustaches. Popular among those seeking how to stop mouth breathing at night without full occlusion, and for reducing the micro-arousals that contribute to poor sleep quality and anxiety around bedtime.',
    safetyNotes: [
      'The central vent is a safety feature but does not replace proper nasal breathing ability.',
      'Avoid if you cannot comfortably breathe through your nose for extended periods.',
      'Popular with CPAP users but always follow your sleep doctor’s guidance.',
      'Skin test recommended for sensitive skin.',
    ],
    howToUse: [
      'Apply to clean, dry skin around mouth.',
      'Align the vent directly over lips center.',
      'Press firmly around edges.',
      'If you feel the need to breathe orally, the vent allows small airflow.',
    ],
    affiliateLink: 'https://www.amazon.co.uk/dp/B0GG5MYR3C?tag=stewraw25-21',
    amazonAsin: 'B0GG5MYR3C', // HASLOM Hypoallergenic with central breathing hole (close to SomniFix vented design, 60 strips) - current popular UK listing; credits stewraw25-21
    image: '/images/somnifix-tape.jpg',
    featured: true,
    inStock: true,
  },
  {
    id: 'p3',
    slug: 'hostage-tape',
    name: 'Hostage Tape',
    brand: 'Hostage Tape',
    category: 'mouth-tape',
    rating: 4.7,
    reviewCount: 967,
    price: '£11.99 / 30 nights',
    priceValue: 11.99,
    bestFor: ['Beards', 'Heavy Mouth Breathers', 'Value'],
    pros: [
      'Outstanding value – great performance at lower price',
      'Designed for "mouth hostage" heavy breathers',
      'Holds extremely well, even with beards',
      'Minimalist black packaging, fun branding',
      'Good adhesion without excessive stickiness on removal',
    ],
    cons: [
      'Slightly thicker material than premium competitors',
      'Fewer "gentle skin" claims',
      'Branding may not appeal to everyone',
    ],
    description: 'Bold, effective, and affordable. Built for serious mouth breathers who want results without breaking the bank.',
    longDescription: 'Hostage Tape has gained a cult following for delivering serious hold and results at a more accessible price. Many users with dense beards report it as the only tape that stays on all night. Strong but fair on skin for most.',
    safetyNotes: [
      'Stronger adhesive – remove slowly and carefully, especially with facial hair.',
      'Standard mouth taping safety rules apply strictly.',
      'May leave slight residue on very sensitive skin (rare).',
    ],
    howToUse: [
      'Best applied to dry skin.',
      'Center over mouth and smooth outward.',
      'For beards: press around contours of facial hair.',
    ],
    affiliateLink: 'https://www.amazon.co.uk/dp/B0C9B492LN?tag=stewraw25-21',
    amazonAsin: 'B0C9B492LN', // Hostage Tape UK - from Amazon.co.uk (beard/CPAP friendly); tag stewraw25-21 via /go/
    image: '/images/hostage-tape.jpg',
    featured: true,
    inStock: true,
  },
  {
    id: 'p4',
    slug: 'zzztape',
    name: 'ZzzTape Pro Sleep Strips',
    brand: 'ZzzTape',
    category: 'mouth-tape',
    rating: 4.4,
    reviewCount: 612,
    price: '£9.99 / 60 strips',
    priceValue: 9.99,
    bestFor: ['Value', 'Beginners', 'Sensitive Skin'],
    pros: [
      'Best value – 60 strips per pack',
      'Very gentle adhesive, great for sensitive skin',
      'Easy to find and reorder',
      'Good starter option to test mouth taping',
    ],
    cons: [
      'Hold not as robust as premium options for side sleepers or hot sleepers',
      'May come loose toward morning for heavy sweaters',
      'Less premium feel and packaging',
    ],
    description: 'Budget-friendly high-volume option. Perfect entry point to try mouth taping without commitment.',
    longDescription: 'ZzzTape offers the most strips per dollar. Many beginners start here to see if mouth taping works for them. While not as premium in materials, the value and gentleness make it popular for light to moderate mouth breathers.',
    safetyNotes: [
      'Good choice for testing tolerance.',
      'If it comes loose often, upgrade to stronger options.',
      'Follow all standard mouth taping precautions.',
    ],
    howToUse: [
      'Apply to clean dry lips.',
      'Use one strip per night.',
      'Store pack in cool dry place.',
    ],
    affiliateLink: 'https://www.amazon.co.uk/dp/B0CJDGFLJ1?tag=stewraw25-21',
    amazonAsin: 'B0CJDGFLJ1', // 60PCS Adult Mouth Tape (value high-volume gentle pack) - solid budget match for ZzzTape Pro; credits stewraw25-21 via /go/
    image: '/images/value-mouth-tape.jpg',
    inStock: true,
  },
  {
    id: 'p5',
    slug: 'mytape',
    name: 'MyoTape Gentle',
    brand: 'MyoTape',
    category: 'mouth-tape',
    rating: 4.5,
    reviewCount: 431,
    price: '£14.99 / 25 nights',
    priceValue: 14.99,
    bestFor: ['Sensitive Skin', 'Children (teens)', 'Light Sleepers'],
    pros: [
      'Extremely gentle – best for sensitive skin and first-timers',
      'Smaller size, less overwhelming',
      'Good for teens learning nasal breathing',
      'Comes with helpful instructional guide',
    ],
    cons: [
      'Smaller surface area – may not suit aggressive mouth breathers',
      'Lower quantity per pack',
      'Premium price for the gentleness',
    ],
    description: 'The gentlest option on the market. Ideal for sensitive skin, beginners, and those easing into the habit.',
    longDescription: 'MyoTape focuses on minimal irritation. Its smaller, softer strips are popular with people who have had reactions to other tapes and with parents introducing the concept to older teens (always under guidance).',
    safetyNotes: [
      'Best entry tape for sensitive skin.',
      'Not intended as primary solution for severe sleep-disordered breathing.',
      'Teen use should be supervised by parent + ideally ENT or sleep specialist.',
    ],
    howToUse: [
      'Perfect for gradual introduction – some users start with half nights.',
      'Remove very slowly in the morning.',
    ],
    affiliateLink: 'https://www.amazon.co.uk/dp/B0G54DFVX7?tag=stewraw25-21',
    amazonAsin: 'B0G54DFVX7', // Gentle mouth tape (similar to MyoTape style) - sourced from Amazon.co.uk search results
    image: '/images/mytape.jpg',
    inStock: true,
  },
  {
    id: 'p6',
    slug: 'sayless',
    name: 'SayLess Mouth Tape',
    brand: 'SayLess',
    category: 'mouth-tape',
    rating: 4.3,
    reviewCount: 289,
    price: '£12.99 / 35 nights',
    priceValue: 12.99,
    bestFor: ['Side Sleepers', 'Value', 'Everyday Use'],
    pros: [
      'Great balance of price, quantity, and performance',
      'Soft fabric that contours well',
      'Stays on reliably for side sleepers',
      'Clean minimalist branding',
    ],
    cons: [
      'Not the strongest for beards or very active sleepers',
      'Newer brand with fewer long-term reviews',
      'Adhesive slightly less "premium" than top two',
    ],
    description: 'Solid all-rounder that punches above its price. Excellent everyday choice for most people.',
    longDescription: 'SayLess delivers reliable performance at a fair price. Users consistently praise the comfort-to-hold ratio. A rising favorite in 2025-2026 review roundups.',
    safetyNotes: [
      'Standard mouth taping safety applies.',
      'Good middle-ground option.',
    ],
    howToUse: [
      'Standard application.',
      'Works well with most sleep positions.',
    ],
    affiliateLink: 'https://www.amazon.co.uk/dp/B0DM9W7Q4G?tag=stewraw25-21',
    amazonAsin: 'B0DM9W7Q4G', // Premium Mouth Tape by Like A Log (30pk, good everyday balance) - solid match for SayLess all-rounder; credits stewraw25-21
    image: '/images/value-mouth-tape.jpg',
    inStock: true,
  },
];

export const allProducts: Product[] = [
  ...mouthTapeProducts,
  // Nasal
  {
    id: 'n1',
    slug: 'breathe-right-clear',
    name: 'Breathe Right Clear Nasal Strips',
    brand: 'Breathe Right',
    category: 'nasal',
    rating: 4.5,
    reviewCount: 4521,
    price: '$11.99 / 30 strips',
    priceValue: 11.99,
    bestFor: ['Congestion', 'Allergies', 'Snoring'],
    pros: ['Drug-free instant relief', 'Clinically proven to open airways', 'Easy to apply and remove', 'Widely available'],
    cons: ['Single-use only', 'Can leave slight mark on nose if worn long'],
    description: 'The gold standard nasal strip trusted by athletes and snorers for decades.',
    longDescription: 'Breathe Right nasal strips gently lift and open nasal passages to improve airflow. Excellent complement or alternative for those who cannot mouth tape due to congestion.',
    safetyNotes: ['For external use only.', 'Discontinue if skin irritation occurs.'],
    howToUse: ['Clean nose. Peel and apply across bridge of nose. Press to activate spring action.'],
    affiliateLink: 'https://www.amazon.co.uk/dp/B017HO49RG?tag=stewraw25-21',
    amazonAsin: 'B017HO49RG', // Breathe Right Clear Nasal Strips - standard UK listing from Amazon.co.uk
    image: '/images/nasal-product.jpg',
    inStock: true,
  },
  {
    id: 'n2',
    slug: 'nasal-dilator-pro',
    name: 'Nasal Dilator Pro (Internal)',
    brand: 'Airway Wellness',
    category: 'nasal',
    rating: 4.2,
    reviewCount: 387,
    price: '£19.99 / 2-pack (reusable)',
    priceValue: 19.99,
    bestFor: ['Athletes', 'Stronger Dilation', 'Reusable'],
    pros: ['Reusable for months', 'Stronger physical dilation than external strips', 'No adhesive on skin'],
    cons: ['Can feel unusual inside nose at first', 'Needs regular cleaning'],
    description: 'Internal nasal dilator for maximum airflow. Popular with athletes and chronic nasal restrictors.',
    longDescription: 'Soft medical silicone internal dilators that physically expand the nasal valve. Many users combine with external strips for best results.',
    safetyNotes: ['Clean thoroughly after each use. Do not share.'],
    howToUse: ['Insert gently into each nostril until secure but comfortable.'],
    affiliateLink: 'https://www.amazon.co.uk/dp/B00B4S61QE?tag=stewraw25-21',
    amazonAsin: 'B00B4S61QE', // Popular internal nasal dilator (Airmax style) widely available UK for sleep/breathing
    image: '/images/nasal-dilator.jpg',
    inStock: true,
  },
  // Gadgets
  {
    id: 'g1',
    slug: 'oura-ring-gen3',
    name: 'Oura Ring Gen3',
    brand: 'Oura',
    category: 'gadgets',
    rating: 4.7,
    reviewCount: 892,
    price: '£239–£439',
    priceValue: 239,
    bestFor: ['Sleep Tracking', 'Recovery Data', 'Long-term Insights'],
    pros: ['Best-in-class sleep staging and readiness score', 'Comfortable 24/7 wear', 'Excellent app and insights', 'Long battery'],
    cons: ['Expensive', 'Subscription for full features after first year', 'Learning curve for data'],
    description: 'The gold standard wearable for serious sleep optimization and recovery tracking.',
    longDescription: 'Oura provides detailed nightly sleep architecture, HRV, temperature trends, and personalized recommendations. Indispensable for data-driven sleep improvement.',
    safetyNotes: ['Not a medical device. Consult professionals for diagnosed conditions.'],
    howToUse: ['Wear consistently. Review daily Readiness and Sleep scores in app.'],
    affiliateLink: 'https://www.amazon.co.uk/dp/B0CSRF8JGG?tag=stewraw25-21',
    amazonAsin: 'B0CSRF8JGG', // Oura Ring Gen3 Heritage (black) - current UK listing; commissions via tag stewraw25-21. For higher rates consider official Oura affiliate + NEXT_PUBLIC_AFF_OURA override
    image: '/images/gadget-tracker.jpg',
    featured: true,
    inStock: true,
  },
  {
    id: 'g2',
    slug: 'eight-sleep-pod-6',
    name: 'Eight Sleep Pod 6',
    brand: 'Eight Sleep',
    category: 'gadgets',
    rating: 4.8,
    reviewCount: 1247,
    price: 'From £2,295 (Pod 6 Cover)',
    priceValue: 2295,
    bestFor: ['Temperature Regulation', 'Hot Sleepers', 'Couples', 'Deep Recovery', 'Athletes'],
    pros: [
      'Active cooling down to 12°C and heating up to 43°C — transformative for hot sleepers',
      'Dual-zone temperature for couples with different preferences',
      'Autopilot adjusts temperature throughout the night based on your sleep stages',
      'Detailed sleep and health tracking (HRV, respiratory rate, sleep stages)',
      'Vibrating alarm wakes you at optimal sleep stage — no jarring sounds',
      'F1 teams and elite athletes use it for recovery (official partnerships)',
    ],
    cons: [
      'Significant investment — Pod 6 Cover starts at £2,295, bundles higher',
      'Monthly membership (£15/mo or £190/yr UK) required for full Autopilot and insights',
      'Hub unit sits beside the bed and requires space',
      'Not compatible with all mattress types (check sizing guide)',
      'Water-based system requires occasional maintenance',
    ],
    description: 'The Pod 6 is Eight Sleep\'s latest temperature-controlled sleep system. With dual-zone cooling/heating, sleep tracking, and Autopilot temperature adjustment, it\'s the most advanced bed cooling tech available in the UK for 2026.',
    longDescription: 'The Eight Sleep Pod 6 represents the cutting edge of sleep technology. Using thermoelectric water circulation, the Pod actively cools or heats your mattress between 12°C and 43°C throughout the night. The Autopilot feature learns your sleep patterns and automatically adjusts temperature during different sleep stages — cooling during deep sleep and warming as you approach waking. Dual-zone control means couples can set completely independent temperatures. The integrated sleep tracker measures heart rate, HRV, respiratory rate, and sleep stages without a wearable. Eight Sleep has partnerships with Formula 1 teams and professional athletes who rely on the Pod for recovery — it\'s become a genuine performance tool for those who take sleep seriously. The vibrating alarm gently wakes you at your lightest sleep phase. While the price and subscription model aren\'t for everyone, hot sleepers and data-driven optimisers consistently report it as the most impactful sleep upgrade they\'ve made.',
    safetyNotes: [
      'Follow the setup guide carefully — the system uses water circulation.',
      'Not recommended for use with electric blankets or heated mattress pads.',
      'Consult your doctor before use if you have circulation disorders or temperature sensitivity conditions.',
      'Keep the Hub unit on a stable surface with adequate ventilation.',
    ],
    howToUse: [
      'Fit the Pod Cover over your existing mattress (check compatibility first).',
      'Position the Hub unit beside the bed and fill with distilled water.',
      'Connect to Wi-Fi and complete setup via the Eight Sleep app.',
      'Set your initial temperature preferences — the app guides you through onboarding.',
      'Autopilot learns your patterns over 1–2 weeks and begins automatic adjustments.',
    ],
    affiliateLink: 'https://www.eightsleep.com/uk/pod-cover/',
    image: '/images/eight-sleep-pod.jpg',
    featured: true,
    inStock: true,
  },
  // Eight Sleep Accessories
  {
    id: 'g3',
    slug: 'eight-sleep-base',
    name: 'Eight Sleep Base',
    brand: 'Eight Sleep',
    category: 'bedding',
    rating: 4.6,
    reviewCount: 342,
    price: '£1,699',
    priceValue: 1699,
    bestFor: ['Pod Users', 'Complete Setup', 'Bed Frame Upgrade'],
    pros: [
      'Purpose-built foundation for Pod 4/5/6 covers',
      'Optimised airflow for the Hub cooling system',
      'Clean, minimal aesthetic that matches the Pod',
      'Solid construction — no squeaks or movement',
    ],
    cons: [
      'Only makes sense if you have or plan to buy a Pod',
      'Significant additional investment on top of Pod price',
      'Limited sizing options compared to generic bed frames',
    ],
    description: 'The official Eight Sleep bed base, designed specifically to work with Pod 4, 5, and 6 covers for optimal cooling performance.',
    longDescription: 'The Eight Sleep Base is engineered as a companion to the Pod system. While the Pod Cover works on most mattresses, the Base ensures optimal airflow underneath for the cooling system to perform at its best. It\'s a premium bed frame with a clean, modern look that matches the Eight Sleep aesthetic. Only worth considering if you\'re committed to the Eight Sleep ecosystem.',
    safetyNotes: [
      'Requires assembly — follow included instructions carefully.',
      'Designed specifically for use with Eight Sleep Pod covers.',
      'Check compatibility with your Pod version before purchasing.',
    ],
    howToUse: [
      'Assemble the Base following the included guide.',
      'Place your mattress with Pod Cover on top.',
      'Position Hub unit with adequate ventilation space.',
    ],
    affiliateLink: 'https://www.eightsleep.com/uk/product/the-base/',
    image: '/images/eight-sleep-pod.jpg',
    inStock: true,
  },
  {
    id: 'g4',
    slug: 'eight-sleep-blanket',
    name: 'Eight Sleep Blanket',
    brand: 'Eight Sleep',
    category: 'bedding',
    rating: 4.5,
    reviewCount: 189,
    price: '£799',
    priceValue: 799,
    bestFor: ['Pod 5/6 Users', 'Extra Warmth Control', 'Cold Sleepers'],
    pros: [
      'Integrates with Pod 5/6 system for temperature control',
      'Extends heating/cooling coverage beyond the mattress',
      'High-quality materials and construction',
      'Useful for cold sleepers who want warming on top as well',
    ],
    cons: [
      'Only compatible with Pod 5 and Pod 6 — not Pod 4',
      'Expensive for a blanket, even a smart one',
      'Requires existing Pod system to function',
    ],
    description: 'A temperature-controlled blanket that integrates with Pod 5 and Pod 6 systems, extending climate control to cover you from above.',
    longDescription: 'The Eight Sleep Blanket connects to your existing Pod 5 or Pod 6 system, allowing temperature regulation from above as well as below. This is particularly useful for cold sleepers who want additional warming, or for those who find the Pod Cover alone doesn\'t quite cover their upper body. It\'s a luxury add-on rather than a necessity — most users find the Pod Cover sufficient.',
    safetyNotes: [
      'Only compatible with Pod 5 and Pod 6 systems.',
      'Follow care instructions for washing.',
      'Do not use with other electric blankets or heating pads.',
    ],
    howToUse: [
      'Connect to your Pod 5/6 Hub following the app instructions.',
      'Use as a top cover — the blanket integrates with your temperature schedule.',
      'Adjust settings via the Eight Sleep app.',
    ],
    affiliateLink: 'https://www.eightsleep.com/uk/product/the-blanket/',
    image: '/images/eight-sleep-pod.jpg',
    inStock: true,
  },
  {
    id: 'g5',
    slug: 'eight-sleep-pillow-cover',
    name: 'Eight Sleep Pillow Cover',
    brand: 'Eight Sleep',
    category: 'bedding',
    rating: 4.4,
    reviewCount: 127,
    price: '£999',
    priceValue: 999,
    bestFor: ['Pod Users', 'Head Temperature Control', 'Hot Sleepers'],
    pros: [
      'Temperature-controlled pillow surface',
      'Integrates with existing Pod system',
      'Addresses head/neck temperature — often overlooked',
      'Can help those who get a hot head at night',
    ],
    cons: [
      'Nearly £1,000 for a pillow cover is steep',
      'Requires an existing Pod system',
      'Niche use case — most people don\'t need this',
    ],
    description: 'A temperature-controlled pillow cover that connects to your Pod system, providing cooling or heating for your head and neck.',
    longDescription: 'The Eight Sleep Pillow Cover extends temperature control to your pillow, addressing a common issue for hot sleepers: even with a cool bed, a warm pillow can disrupt sleep. It connects to your existing Pod system and is controlled through the app. This is a premium accessory for those who find the Pod Cover alone doesn\'t solve their head/neck temperature issues.',
    safetyNotes: [
      'Requires an existing Eight Sleep Pod system.',
      'Follow care and washing instructions carefully.',
      'Check compatibility with your Pod version.',
    ],
    howToUse: [
      'Connect to your Pod Hub following app instructions.',
      'Place over your regular pillow or use standalone.',
      'Adjust temperature via the Eight Sleep app.',
    ],
    affiliateLink: 'https://www.eightsleep.com/uk/product/the-pillow-cover/',
    image: '/images/eight-sleep-pod.jpg',
    inStock: true,
  },
  // Mattresses & Bedding (abbreviated for space)
  {
    id: 'm1',
    slug: 'tempur-pedic-adapt',
    name: 'Tempur-Pedic TEMPUR-Adapt',
    brand: 'Tempur-Pedic',
    category: 'mattresses',
    rating: 4.6,
    reviewCount: 2341,
    price: '£1,499–£2,799 (Queen)',
    priceValue: 1499,
    bestFor: ['Pressure Relief', 'Motion Isolation', 'Back Pain'],
    pros: ['Legendary pressure relief and body contouring', 'Excellent motion isolation for couples', 'Very durable'],
    cons: ['Heavy', 'Slow to respond (classic memory foam feel)', 'Heat retention in some models'],
    description: 'Premium memory foam mattress trusted for decades by sleepers with pain and pressure issues.',
    longDescription: 'Tempur material was developed by NASA. It absorbs movement and cradles the body like no other. Best for those who want to "sink in" and wake with fewer aches.',
    safetyNotes: ['Off-gassing period of 24-72 hours recommended.'],
    howToUse: ['Use on solid foundation. Allow full expansion before first sleep.'],
    affiliateLink: 'https://www.amazon.co.uk/s?k=tempur+pedic+adapt&tag=stewraw25-21',
    // Large ticket item, best via brand direct affiliate program if available (set NEXT_PUBLIC_AFF_TEMPUR_PEDIC). Fallback Amazon search with your tag.
    image: '/images/mattress.jpg',
    inStock: true,
  },
  // Supplements
  {
    id: 's1',
    slug: 'magnesium-glycinate-sleep',
    name: 'Magnesium Glycinate 400mg',
    brand: 'Thorne',
    category: 'supplements',
    rating: 4.7,
    reviewCount: 3120,
    price: '$17 / 60 servings',
    priceValue: 17,
    bestFor: ['Relaxation', 'Muscle Recovery', 'Sleep Onset'],
    pros: ['Highly bioavailable form', 'Calms nervous system without grogginess', 'Supports hundreds of body functions', 'Third-party tested'],
    cons: ['Takes 2-4 weeks for full effect for some', 'Can cause loose stools at high doses'],
    description: 'The most recommended supplement for sleep by functional medicine practitioners.',
    longDescription: 'Magnesium glycinate is gentle on the stomach and has excellent absorption. It supports GABA activity and muscle relaxation, helping you fall asleep faster and deeper.',
    safetyNotes: ['Consult doctor if on medications. Start with lower dose.'],
    howToUse: ['Take 30-60 min before bed. 200-400mg elemental magnesium.'],
    affiliateLink: 'https://www.amazon.co.uk/s?k=magnesium+glycinate+400mg&tag=stewraw25-21',
    // Thorne often best via direct (set NEXT_PUBLIC_AFF_MAGNESIUM). Fallback broad search for glycinate 400mg with tag. Popular generics widely available.
    image: '/images/magnesium-supplement.jpg',
    inStock: true,
  },
  {
    id: 's2',
    slug: 'apigenin-50mg',
    name: 'Apigenin 50mg',
    brand: 'Momentous',
    category: 'supplements',
    rating: 4.4,
    reviewCount: 487,
    price: '$23 / 60 capsules',
    priceValue: 23,
    bestFor: ['Deep Sleep', 'Anxiety Reduction', 'Stacking with Magnesium'],
    pros: ['Natural flavonoid from chamomile', 'Promotes calm without sedation hangover', 'Popular in Andrew Huberman sleep cocktail'],
    cons: ['Research still emerging for sleep specifically', 'Can interact with some medications'],
    description: 'A rising star in evidence-based sleep supplementation.',
    longDescription: 'Apigenin binds to GABA receptors similarly to benzodiazepines but much milder. Many biohackers stack 50mg Apigenin + 300-400mg Magnesium Glycinate + optional L-Theanine 30-60 min before bed.',
    safetyNotes: ['Do not combine with sedatives without medical advice.'],
    howToUse: ['Take with magnesium 45 minutes before desired bedtime.'],
    affiliateLink: 'https://www.amazon.com/s?k=apigenin+50mg&tag=stewraw25-21',
    // Many good generic 50mg options; set NEXT_PUBLIC_AFF_APIGENIN for specific brand program if you join one.
    image: '/images/apigenin-supplement.jpg',
    inStock: true,
  },
  {
    id: 's3',
    slug: 'l-theanine-200mg',
    name: 'L-Theanine 200mg',
    brand: 'Sports Research',
    category: 'supplements',
    rating: 4.6,
    reviewCount: 2840,
    price: '$15 / 60 capsules',
    priceValue: 15,
    bestFor: ['Relaxation without drowsiness', 'Sleep anxiety', 'Stacking'],
    pros: [
      'Promotes calm focus and relaxation',
      'Synergizes perfectly with magnesium and apigenin',
      'No grogginess or dependency',
      'Well studied amino acid from green tea',
    ],
    cons: [
      'Mild effect on its own for some people',
      'Best as part of a stack',
    ],
    description: 'The go-to natural relaxant for better wind-down and deeper sleep.',
    longDescription: 'L-Theanine increases alpha brain waves and GABA without sedation. Combined with magnesium glycinate it is one of the most recommended non-habit forming stacks for insomnia and sleep anxiety worldwide.',
    safetyNotes: [
      'Generally recognized as safe. Consult doctor if pregnant or on medication.',
    ],
    howToUse: [
      'Take 200mg 30-60 minutes before bed, ideally with magnesium.',
    ],
    affiliateLink: 'https://www.amazon.com/s?k=l-theanine+200mg&tag=stewraw25-21',
    amazonAsin: 'B00J2J4N3C',
    image: '/images/magnesium-supplement.jpg',
    inStock: true,
  },
];

// Helper functions
export function getProductBySlug(slug: string): Product | undefined {
  return allProducts.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: Product['category']): Product[] {
  return allProducts.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return allProducts.filter((p) => p.featured);
}

export const bestForOptions = [
  'Side Sleepers',
  'Beards',
  'Sensitive Skin',
  'CPAP Users',
  'Value',
  'Heavy Mouth Breathers',
  'Beginners',
  'Congestion',
  'Sleep Tracking',
  'Temperature Regulation',
  'Relaxation',
];

export const categoryLabels: Record<Product['category'], string> = {
  'mouth-tape': 'Mouth Tape & Sleep Strips',
  'nasal': 'Nasal Strips & Dilators',
  'gadgets': 'Sleep Trackers & Gadgets',
  'mattresses': 'Mattresses & Bedding',
  'supplements': 'Supplements & Routines',
  'bedding': 'Bedroom Optimization',
};
